### ISSUE TITLE
여기 데이터 클래스로 안 하신 이유가 있나욥

### ISSUE THREAD

**Issue by JunJaBoy** [No-swimming/No-swimming-Server#63]
https://github.com/No-swimming/No-swimming-Server/blob/e9f83008e3f386438ef2fbb4c135bd03a668e07a/src/main/kotlin/com/example/noswimmingserver/domain/teacher/domain/Teacher.kt#L8

**Comment by jeongho1209** [comment]
data 클래스를 사용하면 자동으로 여러 가지 메소드를 지원해주는데 연관관계를 맺게 되면 그 메소드들로 인해서 순환 참조가 발생할 수 있습니다.
